apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 3
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-kubernetes
        image: adeweetmanacr.azurecr.io/nginx
        ports:
        - containerPort:8080
