apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-dep
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-kubernetes
        image: adeweetmanacr.azurecr.io/nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello