apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-dep
spec:
  replicas: 3
  minReadySeconds: 10 # wait for 10 seconds after each pod comes up before the next one
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # never have more than one pod down
      maxSurge: 1 # never have more than one extra pod
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-kubernetes
        image: adeweetmanacr.azurecr.io/nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello