apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s
  labels:
    zone: prod
    version: v1    
spec:
  containers:
  - name: hello-kubernetes
    image: adeweetmanacr.azurecr.io/nginx
    ports:
    - containerPort:8080
