Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "docker" do |d|
      d.image = "nginx"
      d.force_host_vm = true
      d.remains_running = true
      d.ports = ["81:80"]
    end

end


