Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "docker" do |d|
      d.build_dir = "."
      d.build_args = ["-t=iis:v1"]
      d.create_args = ["-i"]
      d.ports = ["80:80"]
    end



end


